FROM python:3.11-buster

WORKDIR /src/
COPY ../../requirements.txt /src/requirements.txt

RUN apt-get update && apt-get upgrade -y && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

COPY ../../blog_app /src/blog_app
COPY ../../test_blog_app /src/test_blog_app
COPY ../../instance /src/instance
CMD ["python3", "-m", "blog_app.app"]