services:
  flask:
    container_name: flask_app
    hostname: flask
    build: 
      context: ../
      dockerfile: docker/flask/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - db
      - test
    env_file:
      - ./flask/.env
    networks:
      frontend:
          ipv4_address: 172.19.0.10
      backend:
          ipv4_address: 172.18.0.10
    volumes:
      - type: bind
        source: ../blog_app
        target: /src/blog_app
      - type: bind
        source: ../instance
        target: /src/instance
      - type: bind
        source: ../test_blog_app
        target: /src/test_blog_app
    
  db:
    container_name: dev_db
    image: mysql:latest
    hostname: dev
    restart: always
    ports:
      - 3306:3306
    env_file:
      - db/.env
    networks:
      backend:
        ipv4_address: 172.18.0.100
    
  test:
    container_name: test_db
    image: mysql:latest
    hostname: test
    restart: always
    ports:
      - 33060:3306
    env_file:
      - db/.env
    networks:
      backend:
        ipv4_address: 172.18.0.101

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24